name: titanic-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # for convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on  
      - uses: iterative/setup-cml@v1
      - name: cml_run and train model
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # train model 
          dvc repro -f

      - name: Write CML report 
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --prune
          echo "## Validating results" 
          dvc metrics diff master --show-md >> report.md
          cml-send-comment report.md 